llm:
  api_key: "LLM|688818970790738|pc5HH82Qzhq1-chc_sy5yS1G3gc"

github:
  token: "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"
  username: "ds-brandao"
  
mcp_server:
  url: "http://localhost:8080"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"