version: '3.8'

networks:
  management:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  prodnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  frr-router1:
    build: ./frr-router
    container_name: frr-router
    hostname: frr-router
    privileged: true
    ports:
      - "7777:22"
    volumes:
      - ./test-ssh-keys/authorized_keys:/home/frruser/.ssh/authorized_keys:rw
    networks:
      management:
        ipv4_address: 172.20.0.10
      prodnet:
        ipv4_address: 192.168.100.10

  ovs-switch1:
    build: ./ovs-switch
    container_name: ovs-switch
    hostname: ovs-switch
    privileged: true
    ports:
      - "7778:22"
    volumes:
      - ./test-ssh-keys/authorized_keys:/home/ovsuser/.ssh/authorized_keys:rw
    networks:
      management:
        ipv4_address: 172.20.0.11
      prodnet:
        ipv4_address: 192.168.100.11